name: TikTok Video Scraper

on:
  schedule:
    # Run every Sunday at 6:00 AM UTC (weekly)
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-tiktok:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
    
    - name: Run TikTok scraper
      run: |
        python scripts/tiktok_scraper.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/tiktok-videos.json public/tiktok-videos.html
        git diff --staged --quiet || git commit -m "🎵 Auto-update TikTok videos - $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create deployment comment
      if: success()
      run: |
        echo "✅ TikTok videos updated successfully on $(date)"
        echo "📊 Check the logs for details on videos found and processed"
